modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"

[[mods]]

modId="magicnature"
version="${file.jarVersion}"
displayName="Magic Nature"
logoFile="logo.png"
credits="MrBunny create this mod ^^"
authors="MrBunny/Venarge0411"
description='''



'''

[[dependencies.magicnature]]

modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"

[[dependencies.magicnature]]

modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"