modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"

[[mods]]
modId="magicnature"
version="0.0.1-beta"
displayName="Magic Nature"
logoFile=""
credits="Thanks for this example mod goes to Java"
authors="Venarge0411"
description=''''''

[[dependencies.magicnature]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"

[[dependencies.magicnature]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"